// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIiDq7rBPumbrFge9AmXTuEazrBLH0a4',
    appId: '1:500759118187:web:0a152eb045804b29238c2e',
    messagingSenderId: '500759118187',
    projectId: 'circulahealth',
    authDomain: 'circulahealth.firebaseapp.com',
    storageBucket: 'circulahealth.firebasestorage.app',
    measurementId: 'G-PVEK4H7C27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtczCJczLl15SIYgUuO91VHbeVTvFxzTA',
    appId: '1:500759118187:android:cacaba901503cf41238c2e',
    messagingSenderId: '500759118187',
    projectId: 'circulahealth',
    storageBucket: 'circulahealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzmDMaHFPpqFsdnvJnt2L7Lq026xPFFI',
    appId: '1:500759118187:ios:0deaa6c1fd8ba54f238c2e',
    messagingSenderId: '500759118187',
    projectId: 'circulahealth',
    storageBucket: 'circulahealth.firebasestorage.app',
    iosBundleId: 'com.circula.circulahealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzmDMaHFPpqFsdnvJnt2L7Lq026xPFFI',
    appId: '1:500759118187:ios:0deaa6c1fd8ba54f238c2e',
    messagingSenderId: '500759118187',
    projectId: 'circulahealth',
    storageBucket: 'circulahealth.firebasestorage.app',
    iosBundleId: 'com.circula.circulahealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlIiDq7rBPumbrFge9AmXTuEazrBLH0a4',
    appId: '1:500759118187:web:c7c5e473ad282ee6238c2e',
    messagingSenderId: '500759118187',
    projectId: 'circulahealth',
    authDomain: 'circulahealth.firebaseapp.com',
    storageBucket: 'circulahealth.firebasestorage.app',
    measurementId: 'G-SH0Z0H251D',
  );
}
